# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJzVL3atyhkxn-YpWkH6OsfBxF9yRTyc
"""

import csv

def register():
  with open("users.csv","a",newline="") as f:
    writer = csv.writer(f,delimiter=",")
    email = input("Please enter email: ")
    password = input("Please enter your password: ")
    password1 = input("Please Re-enter your password")
    if password == password1:
        writer.writerow([email,password])
        print("Registration is successful ")
    else:
      print("Please try again")

def login():
    email = input("Please enter your email: ")
    password = input("please enter your password:")
    with open("user.csv","r") as f:
      reader = csv.reader(f, delimiter=",")
      for row in reader:
          if row == [email,password]:
            print("Logged in")
            return True
          print("Please try again")
          return False

register()
login()

import csv

def register():
  with open("users.csv","a",newline="") as f:
    writer = csv.writer(f,delimiter=",")
    email = input("Please enter email: ")
    password = input("Please enter your password: ")
    password1 = input("Please Re-enter your password: ")
    if password == password1:
      print("Password not match")
      if len(password)<5: 
        print("Password length too short or too long")
      if len(password)<16:
        print("Password length too short or too long")
        writer.writerow([email,password])
        print("Registration is successful ")
    else:
      print("Please try again")

def login():
    email = input("Please enter your email: ")
    password = input("please enter your password:")
    with open("user.csv","r") as f:
      reader = csv.reader(f, delimiter=",")
      for row in reader:
          if row == [email,password]:
            print("Logged in")
            return True
          print("Please try again")
          return False

register()
login()